// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzT5zcuNV0OGx_dD-2zpwMd-f9OgRT4_Q',
    appId: '1:495306914666:web:ace63360aaef63287e4313',
    messagingSenderId: '495306914666',
    projectId: 'smart-expense-tracker-244e7',
    authDomain: 'smart-expense-tracker-244e7.firebaseapp.com',
    storageBucket: 'smart-expense-tracker-244e7.firebasestorage.app',
    measurementId: 'G-HCGRSG3XYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBIpAq3XVKkuremPTEpoTV_IrBWnZ4jCs',
    appId: '1:495306914666:android:75ca8c53647a76db7e4313',
    messagingSenderId: '495306914666',
    projectId: 'smart-expense-tracker-244e7',
    storageBucket: 'smart-expense-tracker-244e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzXmhnfiqxfGwfne3g5Pg7Asov1JiTJ8A',
    appId: '1:495306914666:ios:6a24285e5896e0aa7e4313',
    messagingSenderId: '495306914666',
    projectId: 'smart-expense-tracker-244e7',
    storageBucket: 'smart-expense-tracker-244e7.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzXmhnfiqxfGwfne3g5Pg7Asov1JiTJ8A',
    appId: '1:495306914666:ios:6a24285e5896e0aa7e4313',
    messagingSenderId: '495306914666',
    projectId: 'smart-expense-tracker-244e7',
    storageBucket: 'smart-expense-tracker-244e7.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzT5zcuNV0OGx_dD-2zpwMd-f9OgRT4_Q',
    appId: '1:495306914666:web:897e010b97ecc8a87e4313',
    messagingSenderId: '495306914666',
    projectId: 'smart-expense-tracker-244e7',
    authDomain: 'smart-expense-tracker-244e7.firebaseapp.com',
    storageBucket: 'smart-expense-tracker-244e7.firebasestorage.app',
    measurementId: 'G-VSMSVYLBZF',
  );
}
